### ISSUE TITLE
Frequent Audible Pops/Clicks

### ISSUE THREAD

**Issue by phuyuk** [adolfintel/sine-android#2]
I hear frequent, random pops/clicks, loud enough to distract from the experience. The issue is present with several presets I have tried.

Device: SM-P900, Lineage 13

**Comment by adolfintel** [comment]
It's a pretty old device and OS. The current version is optimized for Android 8. Do you want to try an older version that might be more compatible with it? (It has google ads though)

**Comment by phuyuk** [comment]
This is the first audio product to cause trouble on this device. For example, Chromadoze and Binaural Beats - applications that similarly depend on realtime digital processing - run fine. Yes, the tablet is aging, but it's not a dog. Also, your app is consuming little more than 10% CPU. Please explain, specifically, what you mean regarding optimization for Android 8.

**Comment by adolfintel** [comment]
When I say optimization for Android 8 I mean that there were some changes to the sound APIs and they were not tested on older devices.

I remember some people having your problem with the first versions of the app in 2014, and they were caused by the device reporting the wrong sound buffer size [here](https://github.com/adolfintel/sine-android/blob/75bf0fd3eb7f45d389b9c3e09b64e9991f2ff643/SINE/app/src/main/java/com/dosse/bwentrain/sound/backends/android/AndroidSoundBackend.java#L33). The fix for those older devices was removed when I did the android 8 changes. The fix consisted in having a minimum and a maximum buffer size (minimum was 1024 if I remember correctly).

I can try to put it back if you want to test it, or you can try different sizes yourself. Let me know

**Comment by phuyuk** [comment]
The 'pops' are obviously discontinuities in the audio stream, and enforcing a higher minimum buffer is an intuitive solution. Thank you very much for acommodating me (and possibly others, too). I'm keen to use this app, so I would be very grateful for the workaround - perhaps as an option in settings?

**Comment by adolfintel** [comment]
Try this APK: [app-release.zip](https://github.com/adolfintel/sine-android/files/3036945/app-release.zip)
I set the buffer size to a fixed 128kb, let me know if it fixes your problem

**Comment by phuyuk** [comment]
Thank you very much - yes, that fixed it. I appreciate that it's not an elegant solution, so If you are not inclined to impose that workaround on everyone, could you include it as an option in Settings?

**Comment by adolfintel** [comment]
Yea, I can add it as an option. You're the first one to bring this up in literally years though.

**Comment by phuyuk** [comment]
Yeah, I hear you. It doesn't make sense to create a new feature just for me.

And if it really is just me, there might be something else going on here. This device is thoroughly de-bloated (and de-Googled), and I'm generally disciplined about what I install; however, the entire installation is a couple of years old, and perhaps overdue for a fresh reinstall - ROM and apps. Also, there are several Xposed modules running - they are privacy/security related, but maybe one of them is misbehaving (ie. getting too busy). When I have time, I'll  methodically investigate.

In the meantime, I'll keep using the patched install. Thank you very much for that.

**Comment by adolfintel** [comment]
It's ok, I'll add it as an option in the next release, in case anyone needs it.
